from __future__ import annotations
import json
import logging
import pickle
import random
from datetime import datetime
from pathlib import Path

import numpy as np
import torch


class AverageMeter:
    def __init__(self) -> None:
        self.reset()

    def reset(self) -> None:
        self.sum = 0.0
        self.count = 0

    def update(self, value: float, n: int = 1) -> None:
        self.sum += value * n
        self.count += n

    @property
    def average(self) -> float:
        return self.sum / max(self.count, 1)


def seed_everything(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def get_device(device_name: str = "auto") -> torch.device:
    if device_name == "auto":
        if torch.cuda.is_available():
            return torch.device("cuda")
        if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
            return torch.device("mps")
        return torch.device("cpu")
    return torch.device(device_name)


def ensure_dir(path: str | Path) -> Path:
    target = Path(path)
    target.mkdir(parents=True, exist_ok=True)
    return target


def build_run_stamp() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def get_latest_experiment_marker(output_root: str | Path) -> Path:
    return Path(output_root) / "latest_experiment.txt"


def set_latest_experiment(output_root: str | Path, experiment_dir: str | Path) -> None:
    marker = get_latest_experiment_marker(output_root)
    marker.parent.mkdir(parents=True, exist_ok=True)
    marker.write_text(str(Path(experiment_dir).resolve()), encoding="utf-8")


def get_latest_experiment(output_root: str | Path) -> Path:
    marker = get_latest_experiment_marker(output_root)
    if not marker.exists():
        raise FileNotFoundError(
            f"Latest experiment marker not found: {marker}. "
            "Run training first or set experiment_name explicitly."
        )
    return Path(marker.read_text(encoding="utf-8").strip())


def create_experiment_dir(output_root: str | Path, experiment_name: str | None = None) -> Path:
    root = ensure_dir(output_root)
    experiment_name = experiment_name or build_run_stamp()
    experiment_dir = ensure_dir(root / experiment_name)
    set_latest_experiment(root, experiment_dir)
    return experiment_dir


def resolve_experiment_dir(output_root: str | Path, experiment_name: str | None = None) -> Path:
    root = ensure_dir(output_root)
    if experiment_name in (None, "", "latest"):
        experiment_dir = get_latest_experiment(root)
    else:
        experiment_dir = root / experiment_name

    if not experiment_dir.exists():
        raise FileNotFoundError(f"Experiment directory not found: {experiment_dir}")
    return experiment_dir


def setup_logger(name: str, log_file: str | Path) -> logging.Logger:
    logger = logging.getLogger(name)
    logger.setLevel(logging.INFO)
    logger.propagate = False

    for handler in list(logger.handlers):
        logger.removeHandler(handler)
        handler.close()

    log_path = Path(log_file)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    formatter = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")

    file_handler = logging.FileHandler(log_path, encoding="utf-8")
    file_handler.setFormatter(formatter)

    stream_handler = logging.StreamHandler()
    stream_handler.setFormatter(formatter)

    logger.addHandler(file_handler)
    logger.addHandler(stream_handler)
    return logger


def make_serializable(data):
    if isinstance(data, dict):
        return {key: make_serializable(value) for key, value in data.items()}
    if isinstance(data, list):
        return [make_serializable(item) for item in data]
    if isinstance(data, tuple):
        return tuple(make_serializable(item) for item in data)
    if isinstance(data, Path):
        return str(data)
    return data


def save_json(data, path: str | Path) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("w", encoding="utf-8") as file:
        json.dump(make_serializable(data), file, indent=2, ensure_ascii=False)


def save_checkpoint(state: dict, path: str | Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(make_serializable(state), path)


def load_checkpoint(path: str | Path, map_location: str | torch.device = "cpu") -> dict:
    target = Path(path)
    try:
        return torch.load(target, map_location=map_location)
    except pickle.UnpicklingError:
        # Project checkpoints may include trusted metadata fields such as serialized
        # training arguments. PyTorch 2.6+ defaults to weights_only=True, so fall
        # back to full checkpoint loading for checkpoints generated by this project.
        return torch.load(target, map_location=map_location, weights_only=False)


def checkpoint_uses_aux_classifier(checkpoint: dict) -> bool:
    state_dict = checkpoint.get("model", checkpoint)
    return any(key.startswith("aux_classifier.") for key in state_dict.keys())
